"""strip_markers_pre_filing.py — strip inline [OCC_M###] markers from operative
filing text before physical transmission to OCC / FEC / DOJ / House Ethics.

The OCC complaint package carries inline [OCC_M###] marker references in every
operative paragraph at every fact-citation point (FEC PP convention; mirrors the
[FECPP_M###] marker density in the FEC PP referral). The markers are an internal
reviewer aid — they let a substrate engineer at OCC re-derive each numerical
assertion from primary substrate by looking up the marker in
`_provenance_index_occ.json` and running the documented `sql_text` against
`public.v_statute_current` / `lake.*` / `ro_khanna.v3_facts` / public-source
endpoints.

Inline markers are designed to be REMOVED before the package is physically
transmitted to a venue's clerk. The `§A Provenance Appendix` table at the
bottom of OCC_COMPLAINT_KHANNA.md (auto-generated by
`scripts/k_provenance_appendix_build.py`) preserves the marker → fact
mapping in a dedicated catalog block; reviewers who want to drill into a
specific paragraph's substrate can locate the relevant markers via the
appendix's `body_section` column.

This script:
1. Walks each named filing file under OCC_FILING_PACKAGE_V2/.
2. Strips inline `[OCC_M###]` and `[OCC_M###, OCC_M###, ...]` brackets via regex.
3. Optionally also strips the §A Provenance Appendix block (--strip-appendix)
   when the venue prefers a leaner submission. Default leaves the appendix
   intact so the venue retains the catalog if it wants it.
4. Writes stripped output to `<file>.filing.md` (default) or in-place
   (--in-place; refuses to overwrite without --force).
5. Reports a per-file count of removed marker references for audit.

Usage:
    python strip_markers_pre_filing.py                     # all files, .filing.md outputs
    python strip_markers_pre_filing.py --in-place --force  # mutate in place
    python strip_markers_pre_filing.py --strip-appendix    # also drop §A appendix
    python strip_markers_pre_filing.py --files OCC_COMPLAINT_KHANNA.md  # subset

Idempotent: re-running on already-stripped text removes 0 markers and leaves
the file unchanged.

The reverse operation (re-embedding markers from the manifest) is NOT
provided — markers are authored at body-edit time against the manifest's
`first_seen_section` mapping, not regenerated.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

DEFAULT_FILES = [
    "OCC_COMPLAINT_KHANNA.md",
    "DOJ_REFERRAL_KHANNA.md",
    "HOUSE_ETHICS_SUBMISSION_KHANNA.md",
]

# Inline marker pattern: matches `[OCC_M001]` or `[OCC_M001, OCC_M002, ...]`.
# Allows leading/trailing whitespace inside the bracket; comma- or whitespace-
# separated marker IDs. The brackets and a single leading space (when present)
# are consumed so that "fact text [OCC_M001]." → "fact text." (no double space).
INLINE_MARKER_RE = re.compile(
    r" ?\[\s*OCC_M\d+(?:\s*,\s*OCC_M\d+)*\s*\]"
)

# §A Provenance Appendix block: from the H2 header `## Appendix A — Provenance Index`
# through (but not including) the next H2 header (typically `## METHODOLOGY`).
APPENDIX_BLOCK_RE = re.compile(
    r"^## Appendix A — Provenance Index.*?(?=^## )",
    re.MULTILINE | re.DOTALL,
)


def strip_markers(text: str) -> tuple[str, int]:
    """Strip inline [OCC_M###] markers. Returns (stripped_text, n_removed)."""
    n = len(INLINE_MARKER_RE.findall(text))
    return INLINE_MARKER_RE.sub("", text), n


def strip_appendix(text: str) -> tuple[str, bool]:
    """Strip the §A Provenance Appendix block. Returns (stripped_text, removed_bool)."""
    new_text, n = APPENDIX_BLOCK_RE.subn("", text)
    return new_text, n > 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Strip inline [OCC_M###] markers from filing text pre-transmission."
    )
    parser.add_argument(
        "--files",
        nargs="+",
        default=DEFAULT_FILES,
        help="Filing files to process (relative to OCC_FILING_PACKAGE root). "
        f"Default: {' '.join(DEFAULT_FILES)}",
    )
    parser.add_argument(
        "--root",
        default=str(Path(__file__).parent),
        help="OCC_FILING_PACKAGE root directory. Default: directory containing this script.",
    )
    parser.add_argument(
        "--in-place",
        action="store_true",
        help="Mutate files in place instead of writing <file>.filing.md.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Required with --in-place to confirm in-place mutation.",
    )
    parser.add_argument(
        "--strip-appendix",
        action="store_true",
        help="Also drop the §A Provenance Appendix block (default: keep it).",
    )
    args = parser.parse_args()

    if args.in_place and not args.force:
        print(
            "[strip_markers] --in-place requires --force (refusing to overwrite without explicit confirmation)",
            file=sys.stderr,
        )
        return 2

    root = Path(args.root)
    if not root.is_dir():
        print(f"[strip_markers] root not a directory: {root}", file=sys.stderr)
        return 2

    total_removed = 0
    for fname in args.files:
        path = root / fname
        if not path.is_file():
            print(f"[strip_markers] SKIP (not found): {fname}", file=sys.stderr)
            continue

        text = path.read_text(encoding="utf-8")
        new_text, n = strip_markers(text)
        appendix_removed = False
        if args.strip_appendix:
            new_text, appendix_removed = strip_appendix(new_text)

        if args.in_place:
            out_path = path
        else:
            out_path = path.with_suffix(".filing.md")

        out_path.write_text(new_text, encoding="utf-8")
        total_removed += n
        suffix = "  (+appendix stripped)" if appendix_removed else ""
        print(f"  {fname}: {n} marker refs removed -> {out_path.name}{suffix}")

    print(f"[strip_markers] total marker refs removed: {total_removed}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
